- hosts: ubuntu-slave
  become: yes
  tasks:
    - name: install apache2 package
      apt:
        name: apache2
        state: latest
 
    - name: copy index.html file
      copy:
        src: index.html
        dest: /var/www/html

    - name: start apache2 sevice
      service:
        name: apache2
        state: started
        enabled: yes



